### ISSUE TITLE
Organisation: classes and packages

### ISSUE THREAD

**Issue by Mido-mughrabi** [Mido-mughrabi/DEA#6]
some classes should be in separated files, which should be also organised in packages

**Comment by omar-arab-oghli** [comment]
``

**Comment by Mido-mughrabi** [comment]
project has now model package, which in turn has a Compiler package (for the compiler), execGraph package (for the execGraph that will run on a VM), and the Executor(which is the VM that reads a graph and an accepted input set, and can run an input through the Graph)
Project is now ready to be converted into a MVC (or any other suitable) architecture with little to no effort.
